### ISSUE TITLE
prep CRAN release

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/webDatabases#9]
- [ ] rename the package (#1)
- [ ] reduce size/duration of examples (#3)
- [ ] rework package code (#7)
- [ ] remove or fix "BIOSIM" dataset (#6)

-----

- [x] update my email address (861fa784)
- [ ] run tests and update tested R versions in cran-comments
- [ ] check revdeps
- [ ] rebuild package website
